services:
  api:
    container_name: api
    volumes:
      - ./config/config-docker.yml:/go/app/config/config-docker.yml
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    restart: unless-stopped
