server:
  AppVersion: 1.0.0
  Port: :8000
  PprofPort: :5555
  Mode: Development
  ReadTimeout: 10
  WriteTimeout: 10
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: db
  PostgresqlSslmode: false
